### PR TITLE
refactor __init__

### PR DESCRIPTION
**Pull request by 12rambau**
- First I removed the print statement. it's just fine in a CLI but can be bothersome when using a jupyter notebook and even worse when dashboarding. 

- I used "__" variable to set all the information so that user can access them. the version number was out of reach
```python
import forestatrisk as far

print(far.__author__)
print(far.__email__)
print(far.__version__)
print(far.__doc__)
```

- use of a a more pythonic way of testing `environ` variables

### CODE REVIEW

**Comment by 12rambau** [comment]
Hi @ghislainv would you consider this PR or should I close it ?

**Comment by ghislainv** [comment]
Hi @12rambau. Sorry for the delay in considering the PR. I will have a look in the next days.

**Comment by 12rambau** [comment]
no problem I just wanted to help you get rid of gdal for pure python installation but I realized my fork was ahead.

**Comment by ghislainv** [comment]
Thanks to you @12rambau for the PR!

**Pull request merged**
